services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/lanchonete
    ports:
      - 8000:8000
    
  node:
    build:
      context: .
      dockerfile: container_vite/Dockerfile
    volumes:
      - ./:/lanchonete
      - ./:/lanchonete/node-modules
    ports: 
      - 5173:5173
    

volumes:
  lanchonete:
  node-modules:

